Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,8 +26,9 @@ jobs:
         run: ls -l
 
       - name: Run update script
-        cd repo
-        run: bash ./repo/update.sh || { echo "Update script failed"; exit 1; }
+        run: |
+           cd repo
+           bash ./repo/update.sh || { echo "Update script failed"; exit 1; }
 
       - name: Commit updated Packages
         run: |
